version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:7
    container_name: flyway_migrations
    command: -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=1234 migrate
    volumes:
      - ./src/main/resources:/flyway/sql
    depends_on:
      - db