POST http://localhost:8080/api/translate
Content-Type: application/json

{
  "textToTranslate": "привет, мир!",
  "languageFrom": "ru",
  "languageTo": "en"
}


###


POST http://localhost:8080/api/translate
Content-Type: application/json

{
  "textToTranslate": "hello, world!",
  "languageFrom": "en",
  "languageTo": "ru"
}

###