CREATE TABLE translation
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ip_address        VARCHAR(255),
    text_to_translate VARCHAR(255),
    translated_text   VARCHAR(255),
    CONSTRAINT pk_translation PRIMARY KEY (id)
);